name: SQL & Python Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install sqlfluff flake8

      - name: Run SQLFluff
        run: sqlfluff lint src/

      - name: Run Flake8
        run: flake8 src/ --max-line-length=120 --exclude=.venv